# Generated by Django 4.2 on 2023-04-19 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='picture')),
                ('cat', models.CharField(max_length=40)),
                ('desc', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
