# Generated by Django 4.2 on 2023-04-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='latest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('img', models.ImageField(upload_to='picture')),
                ('cat', models.CharField(max_length=40)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
